name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "master" ]
    
jobs:

  build-nextcloud:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Nextcloud Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./Nextcloud
        push: true
        tags: marcus1pierce/nextcloud:29-fpm-${{ matrix.architecture }}
        platforms: linux/${{ matrix.architecture }}
    paths:
      - 'Nextcloud/**'

  build-nextcloud-30:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Nextcloud 30 Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./Nextcloud-30
        push: true
        tags: marcus1pierce/nextcloud:30-fpm-${{ matrix.architecture }}
        platforms: linux/${{ matrix.architecture }}
    paths:
      - 'Nextcloud-30/**'

  build-caddy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Caddy Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./Caddy
        push: true
        tags: marcus1pierce/caddy:2-${{ matrix.architecture }}
        platforms: linux/${{ matrix.architecture }}
    paths:
      - 'Caddy/**'