name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Nextcloud/**'
      - 'Nextcloud-30/**'
      - 'Caddy/**'
      - 'Watchtower/**'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      nextcloud: ${{ steps.filter.outputs.nextcloud }}
      nextcloud30: ${{ steps.filter.outputs.nextcloud30 }}
      caddy: ${{ steps.filter.outputs.caddy }}
      watchtower: ${{ steps.filter.outputs.watchtower }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Check file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            nextcloud:
              - 'Nextcloud/**'
            nextcloud30:
              - 'Nextcloud-30/**'
            caddy:
              - 'Caddy/**'
            watchtower:
              - 'Watchtower/**'

  build-nextcloud:
    needs: check-changes
    if: needs.check-changes.outputs.nextcloud == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Nextcloud Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./Nextcloud
          push: true
          tags: |
            marcus1pierce/nextcloud:29-fpm-${{ matrix.architecture }}
            marcus1pierce/nextcloud:29-fpm-latest
          platforms: linux/${{ matrix.architecture }}

  build-nextcloud-30:
    needs: check-changes
    if: needs.check-changes.outputs.nextcloud30 == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Nextcloud 30 Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./Nextcloud-30
          push: true
          tags: |
            marcus1pierce/nextcloud:30-fpm-${{ matrix.architecture }}
            marcus1pierce/nextcloud:30-fpm-latest
          platforms: linux/${{ matrix.architecture }}

  build-caddy:
    needs: check-changes
    if: needs.check-changes.outputs.caddy == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Caddy Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./Caddy
          push: true
          tags: |
            marcus1pierce/caddy:2-${{ matrix.architecture }}
            marcus1pierce/caddy:2-latest
          platforms: linux/${{ matrix.architecture }}

  build-watchtower:
    needs: check-changes
    if: needs.check-changes.outputs.watchtower == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push Watchtower Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./Watchtower
          push: true
          tags: |
            marcus1pierce/watchtower:latest
            marcus1pierce/watchtower:${{ matrix.architecture }}
          platforms: linux/amd64,linux/arm64